#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mautrix_telegram"
name = "Matrix Telegram bridge"

description.en = "Matrix / Synapse puppeting bridge for Telegram"
description.fr = "Passerelle Matrix / Synapse pour Telegram"
version = "0.2607.0~ynh1"

maintainers = ["thardev"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://maunium.net/go/mautrix-telegram"
code = "https://github.com/mautrix/telegram"
admindoc = "https://docs.mau.fi/bridges/go/telegram/index.html"
fund = "https://github.com/sponsors/tulir"

[integration]
yunohost = ">= 13"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "1G"
ram.build = "128M"
ram.runtime = "128M"

[install]

[install.synapse_instance]
ask.en = "Choose the local Synapse instance to communicate with mautrix_telegram."
ask.fr = "Choisissez l'instance Synapse qui doit communiquer avec mautrix_telegram."
type = "app"
#pattern.regexp = "synapse(__)*[0-9]*"
#pattern.error = "Invalid app selected. Please select a Synapse instance."
help.en = "Usually the Synapse instances contain a number after it is installed more than one time. E.g. synapse__1 will be the second instance."
help.fr = "En général, les instances de Synapse contiennent un numéro après avoir été installées plus d'une fois. Par exemple, synapse__1 sera la deuxième instance."
default = "synapse"

[install.botname]
ask.en = "Choose a local Synapse user name for the Telegram bot."
ask.fr = "Choisissez un nom d'utilisateur Synapse local pour le robot Telegram."
type = "string"
example = "telegrambot"
help.en = "A system user will be created. Invite @telegrambot:localsynapse.servername from an authorized Matrix account to start bridging. Give the Matrix server_name, not the full domain/URL."
help.fr = "Un utilisateur système sera créé. Inviter @telegrambot:localsynapse.servername depuis un compte Matrix autorisé pour démarrer une passerelle. Donner le nom du serveur Matrix, pas le domaine/URL complet."
default = "telegrambot"

[install.encryption]
ask.en = "Enable end-to-bridge encryption?"
ask.fr = "Activer le chiffrement entre Synapse et le bridge ?"
type = "boolean"
help.en = "Only activate if you know the prerequisites and constraints related to E2B."
help.fr = "N'activer que si vous connaissez les prérequis et constraintes liées à E2B."
default = true

[install.botadmin]
ask.en = "Choose the Matrix account administrator of the Telegram bot."
ask.fr = "Choisissez le compte Matrix administrateur du robot Telegram."
type = "string"
example = "@johndoe:localsynapse.servername or @johndoe:matrix.org"
help.en = "The administrator does not need to be a local Synapse account. Valid formats are @johndoe:localsynapse.servername or @johndoe:matrix.org"
help.fr = "L'administrateur peut ne pas être un compte local Synapse. Les formats valables sont @johndoe:localsynapse.servername or @johndoe:matrix.org"
default = "Your main Matrix account"

[install.botusers]
ask.en = "Choose Matrix user(s) authorized to bridge with the Telegram bot."
ask.fr = "Choisissez le/les compte(s) Matrix autorisés à utiliser la passerelle Telegram."
type = "string"
example = "@johndoe:server.name or server.name or *"
help.en = "A remote or local user (@johndoe:server.name),the local server (server.name), a remote server (matrix.org), or all remote/local servers (*) can be authorized. Give the Matrix server_name, not the full domain/URL. It is also possible to specify multiple values by separating them with comma. Example: @johndoe:server.name,domain.tld,matrix.org"
help.fr = "Un compte local ou distant (@johndoe:server.name), le serveur local (server.name), un serveur distant (matrix.org), ou tous les serveurs remote/local (*). Donner le nom du serveur Matrix, pas le domaine/URL complet. Il est également possible de spécifier plusieurs valeurs en les séparant par une virgule. Exemple : @johndoe:server.name,domain.tld,matrix.org"

[install.enable_relaybot]
ask.en = "Choose whether to enable the relay bot feature."
ask.fr = "Choisissez si vous souhaitez activer la fonctionnalité de robot-relai."
help.en = "If enabled, allows to use a single Telegram account (bot) to forward messages from multiple Matrix users. Messages will appear on Telegram as if originating from a single user, with a prefix that indicates who is talking."
help.fr = "Si activé, permet d'utiliser un seul compte Telegram (bot) pour transmettre les messages de multiples utilisateurs Matrix. Les messages apparaîtront sur Telegram comme envoyés par un seul utilisateur, avec un préfixe indiquant leur auteur."
type = "boolean"
default = true

[install.api_id]
ask.en = "Telegram API keys (https://my.telegram.org/apps): ID"
ask.fr = "Clés API Telegram API (https://my.telegram.org/apps): ID"
type = "string"
example = "1234567"
help.en = "Get your own API keys at https://my.telegram.org/apps"
help.fr = "Obtenez vos propres clés API sur https://my.telegram.org/apps"

[install.api_hash]
ask.en = "Telegram API keys (https://my.telegram.org/apps): Hash"
ask.fr = "Clés API Telegram (https://my.telegram.org/apps) : Hash"
type = "string"
example = "tjyd5yge35lbodk1xwzw2jstp90k55qz"
help.en = "Get your own API keys at https://my.telegram.org/apps"
help.fr = "Obtenez vos propres clés API sur https://my.telegram.org/apps"

[resources]
	[resources.sources]
	[resources.sources.main]
	in_subdir = false
	extract = false
	rename = "mautrix-signal"
	amd64.url = "https://github.com/mautrix/telegram/releases/download/v0.2607.0/mautrix-telegram-amd64"
	amd64.sha256 = "28bd1fa3cfd7f20db54e42d78c67a26b6b7b5cbd74a216ccace9b9cc5ff01733"
	arm64.url = "https://github.com/mautrix/telegram/releases/download/v0.2607.0/mautrix-telegram-arm64"
	arm64.sha256 = "5067473dbc1f89edfa5aa36bcfee0a2e3e8e69477cc30a68672b4d971f173033"
    armhf.url = "https://github.com/mautrix/telegram/releases/download/v0.2607.0/mautrix-telegram-arm"
	armhf.sha256 = "973dfa6ddb16183abf818a39bfb99f116d2ed130eec8764b2a6f1ed8b3811d8a"
	autoupdate.strategy = "latest_github_release"
	autoupdate.asset.amd64 = "^mautrix-telegram-amd64$"
	autoupdate.asset.arm64 = "^mautrix-telegram-arm64$"
	autoupdate.asset.armhf = "^mautrix-telegram-arm$"

	[resources.system_user]

	[resources.install_dir]

	[resources.permissions]
#	main.allowed = "all_users"
#	main.auth_header = false

	[resources.ports]
	main.default = 29317

	[resources.apt]
#	packages = "postgresql, python3, zlib1g-dev, libjpeg-dev, libwebp-dev, python3-venv, libpq-dev, libffi-dev, libolm-dev"
    packages = "g++, postgresql, ffmpeg"

	[resources.database]
	type = "postgresql"
