test_format = 1.0

[default]

# ------------
# Tests to run
# ------------

preinstall = """
    sudo yunohost tools update apps
    sudo yunohost app install https://github.com/YunoHost-Apps/synapse_ynh/ -a "domain=$domain&init_main_permission=all_users&server_name=$server_name&is_free_registration=$is_free_registration&jitsi_server=$jitsi_server" --force
    """

# -------------------------------
# Default args to use for install
# -------------------------------

args.botadmin = "@johndoe:server.name"
args.botusers = "server.name"
args.apiid = "1234567"
args.apihash = "0800fc577294c34e0b28ad2839435945"

# -------------------------------
# Commits to test upgrade from
# -------------------------------

test_upgrade_from.bf0ba45.name = "Upgrade from 0.13.0"
