#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression "Loading installation settings..."

app=$YNH_APP_INSTANCE_NAME
synapse_install_dir=$(ynh_app_setting_get --app $synapse_instance --key install_dir)

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

ynh_config_remove_systemd

ynh_config_remove_logrotate

#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

ynh_safe_rm "/etc/matrix-$synapse_instance/app-service/$app.yaml"
$synapse_install_dir/update_synapse_for_appservice.sh || ynh_die --message="Synapse can't restart with the appservice configuration"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
