#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression "Loading installation settings..."

app=$YNH_APP_INSTANCE_NAME

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

ynh_config_remove_systemd

ynh_config_remove_logrotate

#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

# Remove a directory securely
ynh_safe_rm "/etc/matrix-$synapse_instance/app-service/$app.yaml"
/opt/yunohost/matrix-$synapse_instance/update_synapse_for_appservice.sh || ynh_die "Synapse can't restart with the appservice configuration"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
